#!/bin/bash
function prgreen {
	echo -n "|"
	echo -ne "\033[32m$1"
	echo -e "\033[0m|"
}

function prred {
	echo -n "|"
	echo -ne "\033[31m$1"
	echo -e "\033[0m|"
}

if ! [[ -z "$1" ]]
then
	profile=$(grep -Ex "\[$1\]" ~/.aws/credentials | sed -e 's/[^-_A-Za-z0-9]//g')
	echo -n "Loading profile: $profile - "
	if ! [[ "$profile" =~ '^\s*$' ]]
	then
		export AWS_DEFAULT_PROFILE="$1"
		export AWS_EB_PROFILE="$1"
		$(sed -e "0,/$1/d" -ne '1,+1 P' ~/.aws/credentials | awk -F ' ' '{ printf "export %s=%s\n", toupper($1), $3 }')
		prgreen "DONE"
		return 0
	fi
	(>&2 prred "Profile not found:[$1]")
	return 1
else
	(>&2 echo "Usage: $0 [profile]")
	return 1
fi